## STATIC CONFIGURATION
global:
  sendAnonymousUsage: true

log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  mqtt:
    address: ":8883"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "acme@detwald.at"
      storage: acme.json
      httpChallenge:
        entryPoint: http


