## STATIC CONFIGURATION
global:
  sendAnonymousUsage: false

log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  mqtt:
    address: ":1883"
  mqtts:
    address: ":8883"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      storage: acme.json
      httpChallenge:
        entryPoint: http


